enum Routes {
  splashScreen('/'),
  landingScreen('/landing'),
  signUpScreen('/signup'),
  signUpOtpScreen('/signup-otp'),
  signUpFinishScreen('/signup-finish'),
  signInScreen('/signin'),
  forgotPasswordScreen('/forgot-password'),
  forgotPasswordOtpScreen('/forgot-password-otp'),
  forgotPasswordNewPasswordScreen('/forgot-password-new-password'),

  dashboardScreen('/dashboard'),
  createPostScreen('/create-post'),
  updatePostScreen('/update-post'),
  postDetailScreen('/post-detail'),
  spacesScreen('/spaces'),
  spaceMessagesScreen('/space-messages'),
  spaceInvitationsScreen('/space-invitations'),
  spaceDetailScreen('/space-detail'),
  createNewSpaceOneScreen('/create-new-one-space'),
  createNewSpaceTwoScreen('/create-new-two-space'),
  createNewSpaceThreeScreen('/create-new-three-space'),
  coachesScreen('/coaches'),
  athletesScreen('/athletes'),
  coachDetailScreen('/coach-detail'),
  calenderAndBookingScreen('/calender-and-booking'),
  setCoachAvailabilityScreen('/set-coach-availability'),
  coachAvailabilityScreen('/coach-availability'),
  chatroomScreen('/chatroom'),
  chatroomDetailsScreen('/chatroom-details'),
  cameraScreen('/camera'),
  batchPhotoPreviewScreen('/batch-photo-preview'),
  imageEvaluationScreen('/image-evaluation'),
  evaluationResultsScreen('/evaluation-results'),
  favoritePostsScreen('/favorite-posts'),
  reportScreen('/report'),
  promotionsScreen('/promotions'),
  myProfileScreen('/my-profile'),
  otherProfileScreen('/other-profile'),
  searchUserProfileScreen('/search-user-profile'),
  profileEditScreen('/profile-edit'),
  subscriptionScreen('/subscription'),
  athleteBookingsScreen('/athlete-bookings'),
  notificationScreen('/notification'),
  buyMeetingPackageScreen('/buy-meeting-package'),
  followersFollowingScreen('/followers-following');

  const Routes(this.path);
  final String path;
}
